<a href="https://colab.research.google.com/github/NajmulGit/VS_Code_SQL/blob/main/Resources/Blank_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [2]:
%%sql

select
        customerkey
from customer
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   customerkey
0           15
1           23
2           36
3          120
4          180
5          185
6          189
7          210
8          225
9          243

In [3]:
%%sql

select
  s.orderdate,
  COUNT(DISTINCT CASE WHEN c.continent = 'Europe' THEN s.customerkey END) as EU_customer,
  COUNT(DISTINCT case when c.continent = 'North America' then s.customerkey END) as NA_customer,
  COUNT(DISTINCT case when c.continent = 'Australia' then s.customerkey END) as AU_customer
from sales s
left join customer c ON s.customerkey = c.customerkey
where
  s.orderdate between '2023-01-01' AND '2023-12-31'
group by
  orderdate
order by
  orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  eu_customer  na_customer  au_customer
0    2023-01-01            6            5            1
1    2023-01-02           15           31            3
2    2023-01-03           17           44            3
3    2023-01-04           28           46            4
4    2023-01-05           22           57            8
..          ...          ...          ...          ...
359  2023-12-27           26           41            6
360  2023-12-28           24           44            7
361  2023-12-29           19           32            4
362  2023-12-30           25           50           16
363  2023-12-31            1            8            0

[364 rows x 4 columns]

In [4]:
%%sql

select table_name
from information_schema.tables
where table_schema = 'public'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [5]:
%%sql

select *
from product
limit 2

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3

In [6]:
%%sql

select *
from sales
limit 2

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64

In [19]:
%%sql

select
  p.categoryname,
  (s.netprice * s.quantity) * exchangerate
from product p
left join sales s on p.productkey = s.productkey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

                         categoryname  ?column?
0                               Audio     63.49
1                           Computers    423.28
2                      Games and Toys    108.75
3             Cameras and camcorders    1146.75
4                               Audio    950.25
...                               ...       ...
199868  Music, Movies and Audio Books    914.61
199869  Music, Movies and Audio Books    150.18
199870  Music, Movies and Audio Books    147.78
199871                      Computers   2019.62
199872                 Games and Toys     56.83

[199873 rows x 2 columns]

In [26]:
%%sql

select *
from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199868,3398034,1,2024-04-20,2024-04-21,664396,999999,1651,7,159.99,139.19,73.57,EUR,0.94
199869,3398034,2,2024-04-20,2024-04-21,664396,999999,1646,1,159.99,159.99,73.57,EUR,0.94
199870,3398035,0,2024-04-20,2024-04-22,267690,999999,1575,2,60.99,53.67,28.05,CAD,1.38
199871,3398035,1,2024-04-20,2024-04-22,267690,999999,415,5,326.00,293.40,166.20,CAD,1.38
199872,3398035,2,2024-04-20,2024-04-22,267690,999999,1693,6,6.88,6.88,3.16,CAD,1.38

In [27]:
%%sql
select
  SUM(netprice)
from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

          sum
0 64818102.76