<a href="https://colab.research.google.com/github/NajmulGit/VS_Code_SQL/blob/main/Resources/Blank_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

## **Median**

In [ ]:
%%sql

select netprice
from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

        netprice
0          98.97
1         659.78
2          54.38
3         286.69
4         135.75
...          ...
199868    139.19
199869    159.99
199870     53.67
199871    293.40
199872      6.88

[199873 rows x 1 columns]

In [ ]:
%%sql

select
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY netprice) AS median_price
from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median_price
0        191.95

In [ ]:
%%sql
select *
from sales
limit 2

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64

In [ ]:
%%sql
select *
from product
limit 2

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3

In [ ]:
%%sql
select
  p.categoryname,
  PERCENTILE_CONT(0.5) WITHIN group (order by (case when
      orderdate between '2022-01-01' and '2022-12-31' then (netprice*quantity*exchangerate) end )) AS y2022_median_sales,
  PERCENTILE_CONT(0.5) WITHIN group (order by (case
    when orderdate between '2023-01-01' and '2023-12-31' then (netprice*quantity*exchangerate) end)) as y2023_median_sales

from sales s
left join product p on s.productkey = p.productkey
group by
  categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  y2022_median_sales  y2023_median_sales
0                          Audio              257.21              266.59
1        Cameras and camcorders               651.46              672.60
2                    Cell phones              418.60              375.88
3                      Computers              809.70              657.18
4                 Games and Toys               33.78               32.62
5                Home Appliances              791.00              825.25
6  Music, Movies and Audio Books              186.58              159.63
7                   TV and Video              730.46              790.79

# **Advanced Segmentation**

In [ ]:
%%sql

select *
from sales
limit 2

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64

In [ ]:
%%sql

select
  orderdate,
  quantity,
  netprice,
  case
      when quantity>=2 and netprice>= 100 then 'maltiple high value order'
      when netprice>=100 then 'single high value item'
      when quantity>=2 then 'maltiple standard item'
      else 'single standard item'
  end as order_type
from sales
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice                 order_type
0  2015-01-01         1     98.97       single standard item
1  2015-01-01         1    659.78     single high value item
2  2015-01-01         2     54.38     maltiple standard item
3  2015-01-01         4    286.69  maltiple high value order
4  2015-01-01         7    135.75  maltiple high value order
5  2015-01-01         3    434.30  maltiple high value order
6  2015-01-01         1     58.73       single standard item
7  2015-01-01         3     74.99     maltiple standard item
8  2015-01-01         2    113.57  maltiple high value order
9  2015-01-01         1    499.45     single high value item

**Using AND for Multiple Conditions**

In [13]:
%%sql

select
  PERCENTILE_CONT(0.5) within group (order by netprice*quantity*exchangerate)

from sales
where
  orderdate between '2022-01-01' and '2023-12-31'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   percentile_cont
0           398.00

In [27]:
%%sql

with median_value as (
    select
      PERCENTILE_CONT(0.5) within group (order by s.netprice*s.quantity*s.exchangerate) as median

from sales s
where
  orderdate between '2022-01-01' and '2023-12-31'

)

select
  p.categoryname,
  sum(case when
     (s.netprice*s.quantity*s.exchangerate) <mv.median and S.orderdate between '2022-01-01' and '2022-12-31'
     then (s.netprice*s.quantity*s.exchangerate) else null end) as low_net_revenue_2022,

  sum(case when
     (s.netprice*s.quantity*s.exchangerate) >= mv.median AND s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
      then (s.netprice*s.quantity*s.exchangerate) else null end) as high_net_revenue_2022,

  sum(case when
      (s.netprice*s.quantity*s.exchangerate)<mv.median and orderdate between '2023-01-01' and '2023-12-31'
      then (s.netprice*s.quantity*s.exchangerate) else null end) as low_net_rev_2023



  from sales s
left join product p on s.productkey = p.productkey,
median_value mv
group by
  categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,low_net_revenue_2022,high_net_revenue_2022,low_net_rev_2023
0,Audio,222337.83,544600.39,180251.13
1,Cell phones,814449.53,7305215.55,729699.39
2,Cameras and camcorders,133004.54,2249528.02,104869.46
3,TV and Video,272338.29,5542998.32,164275.35
4,Home Appliances,219797.07,6392649.61,176261.35
5,Games and Toys,231979.63,84147.67,206103.36
6,"Music, Movies and Audio Books",685808.49,2303488.80,574958.76
7,Computers,624340.42,17237873.07,590790.31