<a href="https://colab.research.google.com/github/NajmulGit/VS_Code_SQL/blob/main/Resources/Blank_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [2]:
%%sql

select
        customerkey
from customer
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   customerkey
0           15
1           23
2           36
3          120
4          180
5          185
6          189
7          210
8          225
9          243

In [3]:
%%sql

select
  s.orderdate,
  COUNT(DISTINCT CASE WHEN c.continent = 'Europe' THEN s.customerkey END) as EU_customer,
  COUNT(DISTINCT case when c.continent = 'North America' then s.customerkey END) as NA_customer,
  COUNT(DISTINCT case when c.continent = 'Australia' then s.customerkey END) as AU_customer
from sales s
left join customer c ON s.customerkey = c.customerkey
where
  s.orderdate between '2023-01-01' AND '2023-12-31'
group by
  orderdate
order by
  orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  eu_customer  na_customer  au_customer
0    2023-01-01            6            5            1
1    2023-01-02           15           31            3
2    2023-01-03           17           44            3
3    2023-01-04           28           46            4
4    2023-01-05           22           57            8
..          ...          ...          ...          ...
359  2023-12-27           26           41            6
360  2023-12-28           24           44            7
361  2023-12-29           19           32            4
362  2023-12-30           25           50           16
363  2023-12-31            1            8            0

[364 rows x 4 columns]

In [18]:
%%sql

select table_name
from information_schema.tables
where table_schema = 'public'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [21]:
%%sql

select *
from product
limit 2

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3

In [23]:
%%sql

select *
from sales
limit 2

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64

In [40]:
%%sql
select
  DISTINCT p.categoryname,
  EXTRACT(YEAR FROM s.orderdate) as year,
  SUM((s.netprice * s.quantity) * s.exchangerate) as total_net_rev
from product p
left join sales s on p.productkey = s.productkey
where
group by
  p.categoryname,
  EXTRACT(YEAR FROM s.orderdate)
order by
  p.categoryname,
  year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

80 rows affected.

    categoryname  year  total_net_rev
0          Audio  2015      170872.15
1          Audio  2016      335737.84
2          Audio  2017      478188.73
3          Audio  2018      970257.63
4          Audio  2019      930937.96
..           ...   ...            ...
75  TV and Video  2020      994522.55
76  TV and Video  2021     2250754.86
77  TV and Video  2022     5815336.61
78  TV and Video  2023     4412178.23
79  TV and Video  2024      910738.50

[80 rows x 3 columns]